name: CMPE272
dependencies:
  - python>=3.7
  - requests
  - pip
  - pip:
    - jsonpath-ng==1.4.2
    - json_compare
    - pymongo>=3.5
    - mongoengine>=0.17.0
    - Faker
    - six>=1.10.0
    - nltk>=3.4
    - Flask
    - pytest
    - coverage
    - flask-mongoengine
    - Flask-Dance
