from mongoengine import*
from db.reviews import Reviews

class Listings(Document):
    listing_id = StringField(required=True, max_length=200)
    listing_url = StringField(required=True, max_length=200)
    scrape_id = StringField(required=False, max_length=200)
    last_scraped = BooleanField(required=False, default= False)
    name = StringField(required=False, max_length=200)
    summary = StringField(required=False)
    space = IntField(required=False)
    description = StringField(required=False)
    experiences_offered = StringField(required=False)
    neighborhood_overview = StringField(required=False)
    notes = StringField(required=False, max_length=600)
    transit = StringField(required=False, max_length=600)
    access = StringField(required=False, max_length=600)
    interaction = StringField(required=False, max_length=600)
    house_rules  = StringField(required=False, max_length=1000)
    thumbnail_url = URLField(required=False)
    medium_url = URLField(required=False)
    picture_url = URLField(required=False)
    xl_picture_url = URLField(required=False)
    host_id = StringField(required=False, max_length=200)
    host_url = StringField(required=False, max_length=200)
    host_name = StringField(required=False, max_length=200)
    host_since = DateField(required=False)
    host_location = StringField(required=False)
    host_about = StringField(required=False)
    host_response_time = StringField(required=False)
    host_response_rate = StringField(required=False)
    host_acceptance_rate = StringField(required=False)
    host_is_superhost = BooleanField(required=False)
    host_thumbnail_url = URLField(required=False)
    host_picture_url = URLField(required=False)
    host_neighbourhood = StringField(required=False)
    host_listings_count = IntField(required=False)
    host_total_listings_count = IntField(required=False)
    host_verifications = ListField(StringField(required=False))
    host_has_profile_pic = BooleanField(required=False)
    host_identity_verified = BooleanField(required=False)
    street = StringField(required=False, max_length=200)
    neighbourhood = StringField(required=False, max_length=200)
    neighbourhood_cleansed = StringField(required=False, max_length=200)
    neighbourhood_group_cleansed = StringField(required=False, max_length=200)
    city = StringField(required=False, max_length=200)
    state = StringField(required=False, max_length=200)
    zipcode = StringField(required=False, max_length=200)
    market = StringField(required=False, max_length=200)
    smart_location = StringField(required=False, max_length=200)
    country_code = StringField(required=False, max_length=200)
    country= StringField(required=False, max_length=200)
    latitude = StringField(required=False, max_length=200)
    longitude = StringField(required=False, max_length=200)
    is_location_exact = BooleanField(required=False)
    property_type = StringField(required=False, max_length=200)
    room_type = StringField(required=False, max_length=200)
    accommodates = IntField(required=False)
    bathrooms= IntField(required=False)
    bedrooms = IntField(required=False)
    beds = IntField(required=False)
    bed_type = StringField(required=False, max_length=200)
    amenities = ListField(StringField(required=False))
    square_feet = IntField(required=False)
    price = StringField(required=False, max_length=200)
    weekly_price = StringField(required=False, max_length=200)
    monthly_price = StringField(required=False, max_length=200)
    security_deposit = StringField(required=False, max_length=200)
    cleaning_fee = StringField(required=False, max_length=200)
    guests_included = StringField(required=False, max_length=200)
    extra_people = StringField(required=False, max_length=200)
    minimum_nights = IntField(required=False)
    maximum_nights = IntField(required=False)
    calendar_updated = StringField(required=False)
    has_availability = BooleanField(required=False)
    availability_30 = IntField(required=False)
    availability_60 = IntField(required=False)
    availability_90 = IntField(required=False)
    availability_365 = IntField(required=False)
    calendar_last_scraped = DateField(required=False)
    number_of_reviews = IntField(required=False)
    first_review = DateField(required=False)
    last_review  = DateField(required=False)
    review_scores_rating = IntField(required=False)
    review_scores_accuracy = IntField(required=False)
    review_scores_cleanliness = IntField(required=False)
    review_scores_checkin = IntField(required=False)
    review_scores_communication = IntField(required=False)
    review_scores_location = IntField(required=False)
    review_scores_value = IntField(required=False)
    review_list = ReferenceField(Reviews, required=False)
    requires_license = BooleanField(required=False)
    license = StringField(required=False)
    jurisdiction_names = StringField(required=False)
    instant_bookable = BooleanField(required=False)
    is_business_travel_ready = BooleanField(required=False)
    cancellation_policy = StringField(required=True, max_length=200)
    require_guest_profile_picture = BooleanField(required=False, default=False)
    require_guest_phone_verification = BooleanField(required=False, default=False)
    calculated_host_listings_count = IntField(required=False)
    reviews_per_month = IntField(required=False)
    first_available_date=DateField(required=False)
